# Generated by Django 3.2 on 2023-12-30 15:14

import datetime

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="params",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64, null=True),
                size=None,
                verbose_name="params",
                default=list,
                blank=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="periodicity",
            field=models.DurationField(default=datetime.timedelta(days=7), verbose_name="periodicity"),
        ),
    ]
