# Generated by Django 3.2 on 2024-01-01 12:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("task_id", models.UUIDField(editable=False, serialize=False)),
                ("subject", models.CharField(max_length=64, verbose_name="subject")),
                (
                    "status",
                    models.CharField(
                        choices=[("PG", "Pending"), ("OK", "Ok"), ("ER", "Error")],
                        default="PG",
                        max_length=2,
                        verbose_name="status",
                    ),
                ),
                ("description", models.TextField(verbose_name="description", null=True)),
            ],
            options={
                "verbose_name": "Notification Status",
                "verbose_name_plural": "Notification Status",
                "db_table": 'public"."notification_status',
            },
        ),
    ]
