# Generated by Django 5.0 on 2024-01-01 17:36

import django.contrib.postgres.fields
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notificationstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="task_id",
            field=models.UUIDField(editable=False, verbose_name="task_id"),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="updated_at",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="params",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64, null=True),
                blank=True,
                default=list,
                size=None,
                verbose_name="params",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_default=django.db.models.functions.datetime.Now(),
                verbose_name="updated_at",
            ),
        ),
    ]
