# Generated by Django 5.0 on 2024-01-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='finish_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('WAITING', 'WAITING'), ('FAILED', 'FAILED'), ('DONE', 'DONE')], default='WAITING', max_length=64, verbose_name='Status'),
        ),
    ]
