# Generated by Django 5.0 on 2024-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_remove_notification_finish_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationstatus",
            name="notification_type",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("WEBSOCKET", "Websocket"), ("PUSH", "Push"), ("TEST", "TEST")],
                default="EMAIL",
                max_length=10,
                verbose_name="type",
            ),
            preserve_default=False,
        ),
    ]
