# Generated by Django 5.0 on 2024-01-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_notificationstatus_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("WEBSOCKET", "Websocket"), ("PUSH", "Push"), ("TEST", "TEST")],
                default="EMAIL",
                max_length=64,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="notification_type",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("WEBSOCKET", "Websocket"), ("PUSH", "Push"), ("TEST", "TEST")],
                max_length=10,
                verbose_name="notification_type",
            ),
        ),
    ]
