"""user_social.

Revision ID: e4c2bfd0c193
Revises: f7373607520a
Create Date: 2023-11-06 16:42:59.703635

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4c2bfd0c193"
down_revision: Union[str, None] = "f7373607520a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "socialnet",
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("oauth_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_socialnet_id"), "socialnet", ["id"], unique=False)
    op.create_index(op.f("ix_socialnet_oauth_id"), "socialnet", ["oauth_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_socialnet_oauth_id"), table_name="socialnet")
    op.drop_index(op.f("ix_socialnet_id"), table_name="socialnet")
    op.drop_table("socialnet")
    # ### end Alembic commands ###
