"""Additional info

Revision ID: f7373607520a
Revises: f3886ec8e174
Create Date: 2023-10-24 10:34:51.826540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f7373607520a"
down_revision: Union[str, None] = "f3886ec8e174"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("login_record", sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("login_record", sa.Column("ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("login_record", sa.Column("access_jti", sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.add_column("login_record", sa.Column("refresh_jti", sqlmodel.sql.sqltypes.GUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("login_record", "refresh_jti")
    op.drop_column("login_record", "access_jti")
    op.drop_column("login_record", "ip")
    op.drop_column("login_record", "user_agent")
    # ### end Alembic commands ###
